apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: bff-service-argo-app
spec:
  project: default
  source:
    repoURL: https://github.com/thnguyen101/e-learning-project-deployment.git
    targetRevision: HEAD
    path: applications/bff-service/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true