apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- behavior: merge
  files:
  - application-staging.yml
  name: lms-config

patches:
  - path: patch-env.yml

images:
- name: lms-service
  newName: ghcr.io/thnguyen101/lms-service
  newTag: latest

replicas:
- count: 1
  name: lms-service

