client-uri: http://bff-service

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak101:
            issuer-uri: http://el-keycloak/realms/keycloak101

logging:
  level:
    org.springframework.security: debug

bff:
  greeting: Welcome to BFF from Kubernetes environment!