spring:
  security:
    oauth2:
      client:
        provider:
          keycloak101:
            issuer-uri: https://keycloak-domain.com/auth/realms/keycloak101

com:
  c4-soft:
    springaddons:
      oidc:
        client:
          client-uri: https://bff-service-domain.com

bff:
  greeting: Welcome to BFF from Kubernetes environment!