spring:
  security:
    oauth2:
      client:
        provider:
          keycloak101:
            issuer-uri: http://el-keycloak/realms/keycloak101

com:
  c4-soft:
    springaddons:
      oidc:
        client:
          client-uri: http://bff-service
          post-logout-redirect-host: bff-service

bff:
  greeting: Welcome to BFF from Kubernetes environment!