apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bff-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: bff-service
      http:
        paths:
          - path: /bff(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: bff-service
                port:
                  number: 80