apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- behavior: merge
  files:
  - application-staging.yml
  name: bff-config

patches:
  - path: patch-env.yml

images:
- name: bff-service
  newName: ghcr.io/thnguyen101/bff-service
  newTag: fde26affd56fdd69b15f7c224716d5bd04dffebe

replicas:
- count: 1
  name: bff-service

